routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::group(['middleware' => ['auth','verifiedmiddleware']], function() {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('users', \App\Http\Controllers\UserController::class);
    Route::resource('data_banjar', \App\Http\Controllers\DataBanjarController::class);
    Route::resource('roles', \App\Http\Controllers\RoleController::class);
    Route::resource('kelihan_banjar', \App\Http\Controllers\KelihanBanjarController::class);
    Route::resource('permissions', \App\Http\Controllers\PermissionsController::class);
    Route::post('pilihKelihanBr', [App\Http\Controllers\PilihanController::class, 'pilihKelihanBr'])->name('pilihKelihanBr');
    Route::get('jumlahSuara', [App\Http\Controllers\PilihanController::class, 'jumlahSuara'])->name('jumlahSuara');

    Route::get('/conversations' , 'ConversationController@index')->name('conversations.index');
    Route::get('/conversations/{conversation}' , 'ConversationController@show')->name('conversation.show');

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait; // add this trait to your user model

    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'alamat',
        'email',
        'password',
        'profile',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function adminlte_image()
    {
        return 'https://picsum.photos/300/300';
    }

    public function adminlte_desc()
    {
        return 'That\'s a nice guy';
    }

    public function adminlte_profile_url()
    {
        return 'profile/username';
    }

    public function warga_banjar()
    {
        return $this->hasOne(WargaBanjarTjgBenoa::class,'user_id','id');

    }

    public function getAllPermissionsAttribute()
    {
        return $this->allPermissions();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\User;
use App\Models\WargaBanjar;
use Illuminate\Http\Request;
use DataTables;

class UserController extends Controller
{
    function __construct()
    {
        // set permission
        // $this->middleware('permission:user-read', ['only' => ['index', 'show']]);
        // $this->middleware('permission:users-create', ['only' => ['create', 'store']]);
        // $this->middleware('permission:users-update', ['only' => ['edit', 'update']]);
        // $this->middleware('permission:users-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        if ($request->ajax()) {
            $user = User::with('warga_banjar');
            return Datatables::of($user)

                ->addColumn('action', function ($row) {

                    $btn = '<a href="/users/' . $row->id . '" data-toggle="tooltip"  data-id="' . $row->id . '" data-original-title="Edit" class="edit btn btn-primary btn-sm editUser"><i class="fas fa-edit"></i></a>';

                    $btn = $btn . ' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="' . $row->id . '" data-original-title="Delete" class="btn btn-danger btn-sm deleteUser"><i class="fas fa-trash"></i></a>';

                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $dataRole = Role::all();
        return view('users.create',compact('dataRole'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'profile' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'no_kk' => ['required', 'unique:users','max:16', 'min:16'],
            'nik' => ['required', 'unique:users','max:16', 'min:16'],
            'name' => 'required',
            'email' => ['required', 'email', 'unique:users'],
            'alamat' => 'required',
            'tempat_tanggal_lahir' => 'required',
            'jenis_kelamin' => 'required',
            'agama' => 'required',
            'pekerjaan' => 'required',

            'password' => [
                'required',
                'string',
                'min:10',             // must be at least 10 characters in length
                'regex:/[a-z]/',      // must contain at least one lowercase letter
                'regex:/[A-Z]/',      // must contain at least one uppercase letter
                'regex:/[0-9]/',      // must contain at least one digit
                'regex:/[@$!%*#?&]/', // must contain a special character
            ],
            'password_confirm' => 'required|same:password'
        ]);


        $imageName = time() . '.' . $request->profile->extension();

        $request->profile->move(public_path('images'), $imageName);

        $data = [
            'profile'     => $imageName,
            'name' => $request->name,
            'email' => $request->email,
            'alamat' => $request->alamat,
            'password' => bcrypt($request->password),
          
            
        ];

        $dataUser = User::create($data);

        $dataWargaBanjar = [
            'user_id' => $dataUser->id,
            'nik'   => $request->nik,
                'tempat_tanggal_lahir' => $request->tempat_tanggal_lahir,
                'tempekan' => $request->tempekan,
                'alamat_banjar' => $request->alamat_banjar,
                'jenis_kelamin' => $request->jenis_kelamin,
                'agama' => $request->agama,
                'pekerjaan' => $request->pekerjaan,
        ];

        $data = WargaBanjar::create($dataWargaBanjar);
        
        if(isset($request->superadministrator) == 'on'){
            $dataUser->attachRole(1);
        } if(isset($request->administrator) == 'on'){
            $dataUser->attachRole(2);
        } if(isset($request->user) == 'on'){
            $dataUser->attachRole(3);
        }

        return redirect()->back()->with(['success' => 'User Berhasil ditambahkan !']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $users = User::with('warga_banjar')->find($id);
        return view('users.edit', compact('users'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
        $dataUser = User::find($request->id);
        $dataWargaBanjar = WargaBanjar::where('user_id',$request->id)->first();

        //validate form
        $this->validate($request, [
            'profile'     => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'nik' => ['required', 'max:16', 'min:16'],
            'name' => 'required',
            'email' => ['required', 'email', 'unique:users,email,' . $request->id],
            'alamat' => 'required',
            'tempat_tanggal_lahir' => 'required',
            'jenis_kelamin' => 'required',
            'agama' => 'required',
            'pekerjaan' => 'required',

        ]);


        //check if image is uploaded
        if ($request->hasFile('profile')) {

            //upload new image
            $imageName = time() . '.' . $request->profile->extension();
            $request->profile->move(public_path('images'), $imageName);

            //delete old image
            $path = public_path() . "/images/" . $dataUser->profile;
            unlink($path);

            //update post with new image
            $data = [
                'profile'     => $imageName,
                'name'     => $request->name,
                'email'   => $request->email,
                'alamat'   => $request->alamat,
            ];
            $dataUser->update($data);
            $dataWargaBanjarUpdate = [
                'nik'   => $request->nik,
                'tempat_tanggal_lahir' => $request->tempat_tanggal_lahir,
                'tempekan' => $request->tempekan,
                'alamat_banjar' => $request->alamat_banjar,
                'jenis_kelamin' => $request->jenis_kelamin,
                'agama' => $request->agama,
                'pekerjaan' => $request->pekerjaan,
            ];
            $dataWargaBanjar->update($dataWargaBanjarUpdate);
        } else {

            $data =
                [
                    'name'     => $request->name,
                    'email'   => $request->email,
                    'alamat'   => $request->alamat,
                 
                ];

            //update post without image
            $dataUser->update($data);

            $dataWargaBanjarUpdate = [
                'nik'   => $request->nik,
                'tempat_tanggal_lahir' => $request->tempat_tanggal_lahir,
                'tempekan' => $request->tempekan,
                'alamat_banjar' => $request->alamat_banjar,
                'jenis_kelamin' => $request->jenis_kelamin,
                'agama' => $request->agama,
                'pekerjaan' => $request->pekerjaan,
            ];
            $dataWargaBanjar->update($dataWargaBanjarUpdate);
        }

        //redirect to index
        return redirect()->back()->with(['success' => 'User Berhasil Diubah!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/create.blade.php
@extends('adminlte::page')

@section('title', 'Form User')

@section('content_header')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-5">
                <h2>Form User</h2>
            </div>
            <div class="col-md-7" style="float:right;text-align:right">
                <a class="btn btn-primary" href="{{ route('users.index') }}"><i class="fas fa-arrow-left"></i> Back</a>

            </div>
        </div>
    </div>
</div>

@stop

@section('content')
@if(session('status'))
<div class="alert alert-success mb-1 mt-1">
    {{ session('status') }}
</div>
@endif
<div class="card">
    <div class="card-body">
        <form action="{{ route('users.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label class="font-weight-bold">Profile</label>
                        <input type="file" class="form-control @error('profile') is-invalid @enderror" name="profile">

                        <!-- error message untuk title -->
                        @error('profile')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>No KK:</strong>
                        <input type="text" name="nik" class="form-control" placeholder="NIK">
                        @error('nik')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>NIK:</strong>
                        <input type="text" name="nik" class="form-control" placeholder="NIK">
                        @error('nik')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Name:</strong>
                        <input type="text" name="name" class="form-control" placeholder="Nama Lengkap">
                        @error('name')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Tempat Tanggal Lahir:</strong>
                        <input type="text" name="tempat_tanggal_lahir" class="form-control" placeholder="Tempat Tanggal Lahir">
                        @error('tempat_tanggal_lahir')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Email:</strong>
                        <input type="email" name="email" class="form-control" placeholder="Email">
                        @error('email')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">

                    <div class="form-group">
                        <label class="font-weight-bold">Tempekan</label>
                        <select name="tempekan" id="tempekan" class="form-control">
                            <option value="bima">BIMA</option>
                            <option value="arjuna">ARJUNA</option>
                            <option value="nakula">NAKULA</option>
                            <option value="sahadewa">SAHADEWA</option>
                            <option value="yudistira">YUDISTIRA</option>
                        </select>


                        <!-- error message untuk content -->
                        @error('tempekan')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">

                    <div class="form-group">
                        <label for="jenis kelamin" class="font-weight-bold">Jenis Kelamin</label>
                        <div class="radio ">
                            <label><input name="jenis_kelamin" type="radio" value="1">Laki - Laki</label>
                        </div>
                        <div class="radio ">
                            <label><input name="jenis_kelamin" type="radio" value="2">Perempuan</label>
                        </div>
                        @error('jenis_kelamin')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">

                    <div class="form-group">
                        <label class="font-weight-bold">Agama</label>
                        <select name="agama" id="agama" class="form-control">
                            <option value="hindu">HINDU</option>
                            <option value="islam">ISLAM</option>
                            <option value="kristen">KRISTEN</option>
                            <option value="protestan">PROTESTAN</option>
                            <option value="budha">BUDHA</option>
                            <option value="konghucu">KONGHUCU</option>

                        </select>


                        <!-- error message untuk content -->
                        @error('agama')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label class="font-weight-bold">Pekerjaan</label>
                        <select name="pekerjaan" id="pekerjaan" class="form-control">
                            <option value="pegawai_swasta">Pegawai Swasta</option>
                            <option value="pns">PNS</option>
                        </select>
                        <!-- error message untuk content -->
                        @error('agama')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">

                    <div class="form-group">
                        <label class="font-weight-bold">Alamat Banjar</label>
                        <textarea class="form-control @error('alamat_banjar') is-invalid @enderror" name="alamat_banjar" rows="5" placeholder="Masukkan alamat banjar"></textarea>

                        <!-- error message untuk content -->
                        @error('alamat_banjar')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Address:</strong>
                        <textarea name="alamat" class="form-control alamat" cols="50"></textarea>

                        @error('alamat')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                @can('role-select')
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Select Role:</strong>
                        @foreach ($dataRole as $dataRole)
                        <div>
                            <input type="checkbox" class="form-control form-control-sm" id="{{$dataRole->name}}" name="{{$dataRole->name}}">
                            <label class="font-weight-bold" for="horns">{{$dataRole->display_name}}</label>
                        </div>
                        @endforeach

                        @error('dataRole')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                @endcan
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Password:</strong>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1"><i class="fas fa-lock"></i></span>
                            </div>
                            <input name="password" type="password" value="" class="input form-control" id="password" placeholder="password"  aria-label="password" aria-describedby="basic-addon1" />
                            <div class="input-group-append">
                                <span class="input-group-text" onclick="password_show_hide();">
                                    <i class="fas fa-eye" id="show_eye"></i>
                                    <i class="fas fa-eye-slash d-none" id="hide_eye"></i>
                                </span>
                            </div>
                        </div>
                        @error('password')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Confirm Password:</strong>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1"><i class="fas fa-lock"></i></span>
                            </div>
                            <input name="password_confirm" type="password" value="" class="input form-control" id="password_confirm" placeholder="Confirm Password"  aria-label="password" aria-describedby="basic-addon1" />
                            <div class="input-group-append">
                                <span class="input-group-text" onclick="password_show_hide();">
                                    <i class="fas fa-eye" id="show_eye"></i>
                                    <i class="fas fa-eye-slash d-none" id="hide_eye"></i>
                                </span>
                            </div>
                        </div>
                        @error('password_confirm')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <button type="submit" class="btn btn-primary ml-3">Submit</button>
            </div>
        </form>
    </div>
</div>


@stop

@section('css')
<style>
    label.error {
        color: #dc3545;
        font-size: 14px;
    }

    .login_oueter {
        width: 360px;
        max-width: 100%;
    }

    .logo_outer {
        text-align: center;
    }

    .logo_outer img {
        width: 120px;
        margin-bottom: 40px;
    }
</style>
@stop

@section('js')
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
<script>
    function password_show_hide() {
        var x = document.getElementById("password");
        var show_eye = document.getElementById("show_eye");
        var hide_eye = document.getElementById("hide_eye");
        hide_eye.classList.remove("d-none");
        if (x.type === "password") {
            x.type = "text";
            show_eye.style.display = "none";
            hide_eye.style.display = "block";
        } else {
            x.type = "password";
            show_eye.style.display = "block";
            hide_eye.style.display = "none";
        }
    }
</script>
@stop

resources/views/users/index.blade.php
@extends('adminlte::page')

@section('title', 'Users')

@section('content_header')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-5">
                <h2>Users Management</h2>
            </div>
            <div class="col-md-7" style="float:right;text-align:right">
                <a class="btn btn-primary btn-sm" href="{{route('users.create')}}" ><i class="fas fa-plus"></i> Create New User</a>

            </div>
        </div>
    </div>
</div>

@stop

@section('content')

<div class="card">
    <div class="card-body">
        <div class="col-md-12 table-responsive">
            <table class="table table-bordered data-table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Username</th>

                        <th>Email</th>
                        <th>Profile</th>

                        <th width="280px">Action</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>



@stop

@section('css')
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">


<style>
    label.error {
        color: #dc3545;
        font-size: 14px;
    }
</style>
@stop

@section('js')
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
   <script>
        //message with toastr
        @if(session()->has('success'))
        
            toastr.success('{{ session('success') }}', 'BERHASIL!'); 

        @elseif(session()->has('error'))

            toastr.error('{{ session('error') }}', 'GAGAL!'); 
            
        @endif
    </script>


<script type="text/javascript">
    $(document).ready(function() {})
    $(function() {

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

      

        var table = $('.data-table').DataTable({
            processing: "<i class='fas fa-spinner fa-spin fa-3x fa-fw'></i>Processing...",
            serverSide: true,
            ajax: "{{ route('users.index') }}",
            columns: [
                {
                    data: 'id',
                    name: 'id'
                },
                {
                    data: 'name',
                    name: 'name'
                },
                {
                    data: 'username',
                    name: 'username'
                },
             
                {
                    data: 'email',
                    name: 'email'
                },
              
               
             
             
               
                
               
                { data: 'profile' ,
              'render': function ( data) {
                if(data != null){
                    return '<img src="http://blog.local.com:82/images/'+data+'" width="40px">';
                }else{
                            return '<h5 style="color:red">Data Profile Belum Diinput</h5>';
                        }

                }
            },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false
                },
            ]
        });
    
       






    });
</script>
@stop