routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::group(['middleware' => ['auth','verifiedmiddleware']], function() {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('users', \App\Http\Controllers\UserController::class);
    Route::resource('data_banjar', \App\Http\Controllers\DataBanjarController::class);
    Route::resource('roles', \App\Http\Controllers\RoleController::class);
    Route::resource('kelihan_banjar', \App\Http\Controllers\KelihanBanjarController::class);
    Route::resource('permissions', \App\Http\Controllers\PermissionsController::class);
    Route::post('pilihKelihanBr', [App\Http\Controllers\PilihanController::class, 'pilihKelihanBr'])->name('pilihKelihanBr');
    Route::get('jumlahSuara', [App\Http\Controllers\PilihanController::class, 'jumlahSuara'])->name('jumlahSuara');

    Route::get('/conversations' , 'ConversationController@index')->name('conversations.index');
    Route::get('/conversations/{conversation}' , 'ConversationController@show')->name('conversation.show');

});

app/Models/Role.php
<?php

namespace App\Models;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{
    public $guarded = [];
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Permission;
use App\Models\Role;
use Illuminate\Http\Request;
use DataTables;
use Illuminate\Support\Facades\Session;

class RoleController extends Controller
{
    protected $rolesModel;
    protected $permissionModel;

    public function __construct()
    {
        $this->rolesModel = Role::all();
        $this->permissionModel = Permission::all();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        if ($request->ajax()) {
            $role = Role::latest()->get();
            return Datatables::of($role)

                ->addColumn('action', function ($row) {

                    $btn = '<a href="/roles/' . $row->id . '/edit" data-toggle="tooltip"  data-id="' . $row->id . '" data-original-title="Edit" class="edit btn btn-primary btn-sm editUser"><i class="fas fa-edit"></i></a>';

                    $btn = $btn . ' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="' . $row->id . '" id="deleteRole" data-original-title="Delete" class="btn btn-danger btn-sm deleteUser"><i class="fas fa-trash"></i></a>';

                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('roles.index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data = $request->validate([
            'name' => 'required|string|unique:roles,name',
            'display_name' => 'nullable|string',
            'description' => 'nullable|string',
        ]);

        $role = Role::create($data);
        $role->syncPermissions($request->get('permissions') ?? []);

        return redirect(route('roles.index'))->with(['success' => 'Role Berhasil ditambahkan !']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $dataRoles = Role::with('permissions:id')
        ->findOrFail($id);

        $permissions = Permission::all(['id', 'name', 'display_name'])
        ->map(function ($permission) use ($dataRoles) {
            $permission->assigned = $dataRoles->permissions
                ->pluck('id')
                ->contains($permission->id);

            return $permission;
        });

        return view('roles.edit', compact('dataRoles','permissions'));
      
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $role = Role::findOrFail($id);

        $data = $request->validate([
            'display_name' => 'nullable|string',
            'description' => 'nullable|string',
        ]);

        $role->update($data);
        $role->syncPermissions($request->get('permissions'));

        return redirect(route('roles.index'))->with(['success' => 'Role Berhasil diupdate !']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
         //delete post by ID
         Role::where('id', $id)->delete();

         //return response
         return response()->json([
             'success' => true,
             'message' => 'Data Role Berhasil Dihapus!.',
         ]); 
    }
}

resources/views/roles/create.blade.php
@extends('adminlte::page')

@section('title', 'Form User')

@section('content_header')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-5">
                <h2>Form Roles</h2>
            </div>
            <div class="col-md-7" style="float:right;text-align:right">
                <a class="btn btn-primary" href="{{ route('roles.index') }}"><i class="fas fa-arrow-left"></i> Back</a>

            </div>
        </div>
    </div>
</div>

@stop

@section('content')
@if(session('status'))
<div class="alert alert-success mb-1 mt-1">
    {{ session('status') }}
</div>
@endif
<div class="card">
    <div class="card-body">
        <form action="{{ route('roles.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label class="font-weight-bold">Role Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" placeholder="Name">

                        <!-- error message untuk title -->
                        @error('name')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label class="font-weight-bold">Role Display</label>
                        <input type="text" class="form-control @error('display_name') is-invalid @enderror" name="display_name" placeholder="Display Name">

                        <!-- error message untuk title -->
                        @error('display_name')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Description:</strong>
                        <input type="text" name="description" class="form-control" placeholder="Deskripsi Role">
                        @error('nik')
                        <div class="alert alert-danger mt-1 mb-1">{{ $description }}</div>
                        @enderror
                    </div>
                </div>
                <button type="submit" class="btn btn-primary ml-3">Submit</button>
            </div>
        </form>
    </div>
</div>


@stop

@section('css')
<style>
    label.error {
        color: #dc3545;
        font-size: 14px;
    }

    .login_oueter {
        width: 360px;
        max-width: 100%;
    }

    .logo_outer {
        text-align: center;
    }

    .logo_outer img {
        width: 120px;
        margin-bottom: 40px;
    }
</style>
@stop

@section('js')
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
<script>
    function password_show_hide() {
        var x = document.getElementById("password");
        var show_eye = document.getElementById("show_eye");
        var hide_eye = document.getElementById("hide_eye");
        hide_eye.classList.remove("d-none");
        if (x.type === "password") {
            x.type = "text";
            show_eye.style.display = "none";
            hide_eye.style.display = "block";
        } else {
            x.type = "password";
            show_eye.style.display = "block";
            hide_eye.style.display = "none";
        }
    }
</script>
@stop

resources/views/roles/edit.blade.php
@extends('adminlte::page')

@section('title', 'Form User')

@section('content_header')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-5">
                <h2>Form Roles</h2>
            </div>
            <div class="col-md-7" style="float:right;text-align:right">
                <a class="btn btn-primary" href="{{ route('roles.index') }}"><i class="fas fa-arrow-left"></i> Back</a>

            </div>
        </div>
    </div>
</div>

@stop

@section('content')
@if(session('status'))
<div class="alert alert-success mb-1 mt-1">
    {{ session('status') }}
</div>
@endif
<div class="card">
    <div class="card-body">
        <form action="{{ route('roles.update', $dataRoles->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label class="font-weight-bold">Role Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" placeholder="Name" value="{{$dataRoles->name}}">

                        <!-- error message untuk title -->
                        @error('name')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label class="font-weight-bold">Role Display</label>
                        <input type="text" class="form-control @error('display_name') is-invalid @enderror" name="display_name" placeholder="Display Name" value="{{$dataRoles->display_name}}">

                        <!-- error message untuk title -->
                        @error('display_name')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Description:</strong>
                        <input type="text" name="description" class="form-control" placeholder="Deskripsi Role" value="{{$dataRoles->description}}">
                        @error('description')
                        <div class="alert alert-danger mt-1 mb-1">{{ $description }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Permissions</strong>
                        <div class="col-md-12">

                            <select class="select2-multiple form-control" name="permissions[]" multiple="multiple" id="select2Multiple">
                                @foreach ($permissions as $key=>$permissionsvalue)
                                @foreach ($dataRoles->permissions as $key1=>$permissionsvalue1)
                                @if($permissions[$key]->id == $dataRoles->permissions[$key1]->id)
                                <option value="{{ $permissions[$key]->id }}" {{ ( $permissions[$key]->id == $dataRoles->permissions[$key1]->id) ? 'selected' : '' }}> {{ $permissions[$key]->name }} </option>
                                
                                @endif
                                @endforeach
                                <option value="{{ $permissions[$key]->id }}"> {{ $permissions[$key]->name }} </option>


                                @endforeach

                            </select>
                        </div>
                        @error('permissions')
                        <div class="alert alert-danger mt-1 mb-1">{{ $description }}</div>
                        @enderror
                    </div>
                </div>
                <button type="submit" class="btn btn-primary ml-3">Submit</button>
            </div>
        </form>
    </div>
</div>


@stop

@section('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.js"></script>
<style>
    label.error {
        color: #dc3545;
        font-size: 14px;
    }

    .login_oueter {
        width: 360px;
        max-width: 100%;
    }

    .logo_outer {
        text-align: center;
    }

    .logo_outer img {
        width: 120px;
        margin-bottom: 40px;
    }
</style>
@stop

@section('js')
<script>
    $(document).ready(function() {
        // Select2 Multiple
        $('.select2-multiple').select2({
            placeholder: "Select",
            allowClear: true
        });

    });
</script>
@stop

resources/views/roles/index.blade.php
@extends('adminlte::page')

@section('title', 'Data Roles')

@section('content_header')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-5">
                <h2>Roles Management</h2>
            </div>
            <div class="col-md-7" style="float:right;text-align:right">
                <a class="btn btn-primary btn-sm" href="{{route('roles.create')}}" ><i class="fas fa-plus"></i> Create New Roles</a>

            </div>
        </div>
    </div>
</div>

@stop

@section('content')

<div class="card">
    <div class="card-body">
        <div class="col-md-12 table-responsive">
            <table class="table table-bordered data-table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Display Name</th>
                        <th>Deskripsi</th>
                    

                        <th width="280px">Action</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>



@stop

@section('css')
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">


<style>
    label.error {
        color: #dc3545;
        font-size: 14px;
    }
</style>
@stop

@section('js')
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
   <script>
        //message with toastr
        @if(session()->has('success'))
        
            toastr.success('{{ session('success') }}', 'BERHASIL!'); 

        @elseif(session()->has('error'))

            toastr.error('{{ session('error') }}', 'GAGAL!'); 
            
        @endif
    </script>


<script type="text/javascript">
    $(function() {

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

      

        var table = $('.data-table').DataTable({
            processing: "<i class='fas fa-spinner fa-spin fa-3x fa-fw'></i>Processing...",
            serverSide: true,
            ajax: "{{ route('roles.index') }}",
            columns: [
                {
                    data: 'id',
                    name: 'id'
                },
                {
                    data: 'name',
                    name: 'name'
                },
                {
                    data: 'display_name',
                    'render': function ( data) {
                        if(data != null){
                            return '<h5>'+data+'</h5>';
                        }else{
                            return '<h5 style="color:red">Display Name belum diinput</h5>';
                        }
                    },
                },
                {
                    data: 'description',
                    'render': function ( data) {
                        if(data != null){
                            return '<h5>'+data+'</h5>';
                        }else{
                            return '<h5 style="color:red">Deskripsi belum diinput</h5>';
                        }
                    },
                },
              
              
               
               
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false
                },
            ]
        });
    
       
           $('body').on('click', '#deleteRole', function () {

        let role_id = $(this).data('id');
        let token   = $("meta[name='csrf-token']").attr("content");

        Swal.fire({
            title: 'Apakah Kamu Yakin?',
            text: "ingin menghapus data ini!",
            type: 'warning',
            showCancelButton: true,
            cancelButtonText: 'TIDAK',
            confirmButtonText: 'YA, HAPUS!'
        }).then((result) => {
            if (result.value) {


                //fetch to delete data
                $.ajax({

                    url: `/roles/${role_id}`,
                    type: "DELETE",
                    cache: false,
                    data: {
                        "_token": token
                    },
                    success:function(response){ 
                        
                        //show success message
                        Swal.fire({
                            type: 'success',
                            type: 'success',
                            title: `${response.message}`,
                            showConfirmButton: false,
                            timer: 3000
                        });
                        table.ajax.reload();


                        //remove post on table
                        $(`#index_${role_id}`).remove();
                    }
                });

                
            }
        })
        
    });





    });
</script>
@stop